# Generated by Django 2.2 on 2020-12-07 11:51

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('logo', models.ImageField(default='static/dashboard/dist/img/logo.png', upload_to=app.models.upload_logo)),
                ('header_color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
                ('sidebar_color', models.CharField(max_length=7)),
                ('footer_color', models.CharField(max_length=7)),
                ('default_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
