# Generated by Django 2.2 on 2020-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_setting_default_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_profile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
