# Generated by Django 2.2 on 2021-04-15 09:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_setting_default_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.FileField(upload_to=app.models.upload_logo)),
                ('config_type', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='column',
            name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentTypeLookup',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='entityrelation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='entityrelation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='socialtenure',
            name='party',
        ),
        migrations.RemoveField(
            model_name='socialtenure',
            name='spatialUnit',
        ),
        migrations.RemoveField(
            model_name='socialtenure',
            name='tenureTypeList',
        ),
        migrations.RemoveField(
            model_name='socialtenure',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='valuelist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='valuelist',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CodeValue',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityRelation',
        ),
        migrations.DeleteModel(
            name='SocialTenure',
        ),
        migrations.DeleteModel(
            name='UserConfig',
        ),
        migrations.DeleteModel(
            name='Validity',
        ),
        migrations.DeleteModel(
            name='ValueList',
        ),
    ]
