# Generated by Django 2.2 on 2021-04-15 09:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210415_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='config_file',
            field=models.FileField(upload_to=app.models.upload_config),
        ),
    ]
