# Generated by Django 2.2 on 2022-01-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210415_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_url', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Kobo Configs',
            },
        ),
    ]
