# Generated by Django 2.2 on 2022-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_web_user',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access the web/stdm dashboard'),
        ),
    ]
