# Generated by Django 2.2 on 2021-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdm_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='profile',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
