# Generated by Django 2.2 on 2021-02-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdm_config', '0002_chart_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
